blank_issues_enabled: true
contact_links:
  - name: New feedback experience
    url: https://learn.microsoft.com/office/new-feedback
    about: Weâ€™re transitioning our feedback experience away from GitHub Issues. For more information, select Open.